"""Curated genre data — the source of truth for assets/genre_graph.json.

Authored here rather than hand-written as JSON: 350 nodes of JSON is not
reviewable in a diff, and the compact tuple form below is. `build_genre_graph.py`
expands it; `validate_genre_graph.py` enforces the invariants.

Provenance
----------
Genre *names* follow MusicBrainz where a match exists (CC0, see
tools/musicbrainz_genres.txt). Lineage, tempo and era are facts researched from
public sources — Ishkur's Guide to Electronic Music for the electronic tree,
Beatport's commercial genre list for naming, and the usual DJ tempo references.
No third-party dataset is copied; energy/valence/mood are our own judgements.

Field guide
-----------
Each row is:

    (id, name, family, parents, aka, bpm, era, energy, valence, moods, near)

id       kebab-case, stable, the key everything else references
name     display name
family   one of FAMILIES
parents  ids this descends from; () for a family root
aka      alternative spellings and abbreviations users actually type
bpm      (low, high) typical tempo. The single most useful hard fact we have.
era      (start_year, end_year_or_None)
energy   0..1 arousal — how activating it is (Russell's circumplex)
valence  0..1 pleasantness — dark/tense at 0, bright/euphoric at 1
moods    mood ids this genre suits
near     ((id, weight), ...) sideways neighbours; parent/child links are implicit

Weights on `near` are "how likely is someone who likes A to accept B", not
similarity in the abstract. They are deliberately asymmetric-friendly: the graph
symmetrises them at build time by taking the max, because a one-way edge is
almost always an authoring oversight rather than a real claim.
"""

FAMILIES = {
    "electronic": "Electronic",
    "hiphop": "Hip-Hop",
    "rock": "Rock",
    "metal": "Metal",
    "pop": "Pop",
    "jazz": "Jazz",
    "classical": "Classical",
    "folk": "Folk & Country",
    "soul": "Soul & R&B",
    "latin": "Latin",
    "global": "Global",
    "experimental": "Ambient & Experimental",
}

# Mood ids referenced by genres below and defined in MOODS at the bottom.
# Kept short on purpose: a mood the listener can't picture is a mood they won't
# tap, and every extra one dilutes the ones that work.

E = None  # ongoing era

GENRES = [
    # ─── Electronic · roots ────────────────────────────────────────────────
    ("electronic", "Electronic", "electronic", (), ("edm", "dance", "electronic music"),
     (60, 200), (1950, E), 0.6, 0.6, ("party", "focus"), ()),

    # ─── House ─────────────────────────────────────────────────────────────
    ("house", "House", "electronic", ("electronic",), ("house music",),
     (118, 128), (1981, E), 0.65, 0.75, ("party", "commute"),
     (("techno", 0.6), ("disco", 0.7), ("garage-house", 0.6))),
    ("chicago-house", "Chicago House", "electronic", ("house",), ("classic house",),
     (118, 127), (1981, E), 0.65, 0.75, ("party",), (("acid-house", 0.8), ("disco", 0.6))),
    ("acid-house", "Acid House", "electronic", ("chicago-house",), ("acid", "303"),
     (118, 130), (1985, E), 0.7, 0.6, ("party", "late-night"),
     (("acid-techno", 0.8), ("tech-house", 0.5))),
    ("deep-house", "Deep House", "electronic", ("house",), ("deephouse",),
     (118, 125), (1985, E), 0.45, 0.7, ("late-night", "chill", "wind-down"),
     (("lounge", 0.6), ("dub-techno", 0.5), ("jazz-house", 0.7), ("afro-house", 0.6))),
    ("tech-house", "Tech House", "electronic", ("house", "techno"), ("techhouse",),
     (122, 128), (1993, E), 0.7, 0.6, ("party", "workout"),
     (("minimal-techno", 0.7), ("microhouse", 0.6))),
    ("progressive-house", "Progressive House", "electronic", ("house",), ("prog house",),
     (124, 130), (1990, E), 0.65, 0.7, ("commute", "party"),
     (("melodic-house-techno", 0.8), ("trance", 0.6))),
    ("electro-house", "Electro House", "electronic", ("house",), ("electrohouse",),
     (125, 135), (2000, E), 0.85, 0.7, ("party", "workout"),
     (("big-room", 0.8), ("fidget-house", 0.6))),
    ("big-room", "Big Room House", "electronic", ("electro-house",), ("bigroom", "mainstage"),
     (126, 132), (2010, E), 0.9, 0.75, ("party", "workout"), (("festival-trance", 0.7),)),
    ("future-house", "Future House", "electronic", ("house",), (),
     (122, 128), (2013, E), 0.75, 0.75, ("party", "commute"), (("bass-house", 0.7),)),
    ("bass-house", "Bass House", "electronic", ("house",), ("g-house",),
     (126, 130), (2012, E), 0.85, 0.55, ("party", "workout"), (("uk-bass", 0.7),)),
    ("fidget-house", "Fidget House", "electronic", ("house",), (),
     (125, 132), (2006, 2012), 0.85, 0.6, ("party",), ()),
    ("microhouse", "Microhouse", "electronic", ("house", "minimal-techno"), ("minimal house",),
     (120, 126), (1997, E), 0.5, 0.6, ("focus", "late-night"), (("minimal-techno", 0.85),)),
    ("jazz-house", "Jazz House", "electronic", ("house",), ("nu jazz house",),
     (118, 125), (1990, E), 0.5, 0.8, ("chill", "wind-down", "late-night"),
     (("nu-jazz", 0.8), ("broken-beat", 0.6))),
    ("afro-house", "Afro House", "electronic", ("house",), ("afrohouse",),
     (118, 124), (2005, E), 0.6, 0.75, ("party", "commute"),
     (("amapiano", 0.7), ("tribal-house", 0.8), ("afrobeats", 0.5))),
    ("tribal-house", "Tribal House", "electronic", ("house",), (),
     (122, 128), (1990, E), 0.7, 0.65, ("party",), ()),
    ("soulful-house", "Soulful House", "electronic", ("house",), ("vocal house",),
     (118, 125), (1990, E), 0.55, 0.85, ("chill", "commute"), (("gospel-house", 0.8), ("disco", 0.6))),
    ("gospel-house", "Gospel House", "electronic", ("soulful-house",), (),
     (118, 126), (1990, E), 0.6, 0.9, ("uplifting",), ()),
    ("french-house", "French House", "electronic", ("house",), ("filter house", "french touch"),
     (118, 126), (1995, E), 0.7, 0.85, ("party", "commute"), (("disco", 0.8), ("nu-disco", 0.85))),
    ("nu-disco", "Nu-Disco", "electronic", ("house", "disco"), ("nudisco",),
     (110, 124), (2002, E), 0.6, 0.85, ("party", "commute"), (("italo-disco", 0.7),)),
    ("garage-house", "Garage House", "electronic", ("house",), ("new jersey sound",),
     (120, 128), (1984, E), 0.6, 0.8, ("party",), (("uk-garage", 0.7),)),
    ("amapiano", "Amapiano", "electronic", ("house",), ("piano", "yanos"),
     (110, 118), (2012, E), 0.5, 0.8, ("party", "chill", "commute"),
     (("gqom", 0.6), ("afro-house", 0.7), ("three-step", 0.8))),
    ("three-step", "3-Step", "electronic", ("amapiano",), ("threestep",),
     (110, 122), (2023, E), 0.5, 0.6, ("late-night", "chill"), (("gqom", 0.7), ("deep-house", 0.6))),
    ("gqom", "Gqom", "electronic", ("house",), (),
     (120, 130), (2010, E), 0.75, 0.4, ("party", "late-night"), ()),
    ("baile-funk", "Baile Funk", "electronic", ("electronic",), ("funk carioca", "brazilian funk"),
     (125, 135), (1990, E), 0.85, 0.7, ("party", "workout"), (("phonk-brazilian", 0.7),)),

    # ─── Techno ────────────────────────────────────────────────────────────
    ("techno", "Techno", "electronic", ("electronic",), (),
     (125, 150), (1985, E), 0.75, 0.45, ("party", "workout", "focus"),
     (("house", 0.6), ("electro", 0.6))),
    ("detroit-techno", "Detroit Techno", "electronic", ("techno",), ("classic techno",),
     (125, 135), (1985, E), 0.7, 0.6, ("focus", "commute"), (("electro", 0.7),)),
    ("minimal-techno", "Minimal Techno", "electronic", ("techno",), ("minimal",),
     (125, 135), (1994, E), 0.6, 0.45, ("focus", "late-night"), (("dub-techno", 0.8),)),
    ("dub-techno", "Dub Techno", "electronic", ("minimal-techno",), ("basic channel sound",),
     (118, 130), (1993, E), 0.4, 0.45, ("late-night", "focus", "wind-down"),
     (("ambient-techno", 0.85), ("deep-house", 0.5))),
    ("ambient-techno", "Ambient Techno", "electronic", ("techno", "ambient"), (),
     (110, 130), (1990, E), 0.35, 0.6, ("focus", "wind-down"), ()),
    ("acid-techno", "Acid Techno", "electronic", ("techno", "acid-house"), (),
     (130, 145), (1990, E), 0.85, 0.4, ("party", "workout"), ()),
    ("hard-techno", "Hard Techno", "electronic", ("techno",), ("hardtechno", "schranz"),
     (140, 160), (1995, E), 0.95, 0.35, ("workout", "party"),
     (("industrial-techno", 0.8), ("hardgroove", 0.7))),
    ("hardgroove", "Hardgroove Techno", "electronic", ("hard-techno",), ("hard groove", "groove techno"),
     (140, 152), (1998, E), 0.9, 0.5, ("workout", "party"), (("tribal-house", 0.4),)),
    ("industrial-techno", "Industrial Techno", "electronic", ("techno",), (),
     (130, 150), (1990, E), 0.9, 0.2, ("workout", "late-night"), (("ebm", 0.7), ("industrial", 0.75))),
    ("peak-time-techno", "Peak Time Techno", "electronic", ("techno",), ("driving techno",),
     (132, 145), (2015, E), 0.9, 0.45, ("party", "workout"), (("hard-techno", 0.8),)),
    ("melodic-house-techno", "Melodic House & Techno", "electronic", ("techno", "house"), ("melodic techno",),
     (120, 126), (2014, E), 0.6, 0.65, ("commute", "late-night", "focus"),
     (("progressive-house", 0.8), ("organic-house", 0.7))),
    ("organic-house", "Organic House", "electronic", ("melodic-house-techno",), ("downtempo house",),
     (110, 122), (2015, E), 0.45, 0.7, ("chill", "wind-down", "focus"), (("downtempo", 0.7),)),
    ("electro", "Electro", "electronic", ("electronic",), ("electro funk", "electrofunk"),
     (110, 135), (1982, E), 0.7, 0.6, ("party", "commute"), (("electro-bass", 0.8), ("breakbeat", 0.6))),
    ("electro-bass", "Miami Bass", "electronic", ("electro",), ("booty bass",),
     (120, 140), (1985, E), 0.8, 0.7, ("party",), ()),
    ("electroclash", "Electroclash", "electronic", ("electro",), (),
     (120, 135), (1998, 2008), 0.8, 0.6, ("party",), (("synthpop", 0.7),)),
    ("ebm", "EBM", "electronic", ("industrial",), ("electronic body music",),
     (120, 140), (1980, E), 0.8, 0.3, ("workout", "late-night"), ()),

    # ─── Trance ────────────────────────────────────────────────────────────
    ("trance", "Trance", "electronic", ("electronic",), (),
     (128, 145), (1990, E), 0.75, 0.75, ("commute", "workout", "uplifting"),
     (("progressive-house", 0.6),)),
    ("progressive-trance", "Progressive Trance", "electronic", ("trance",), (),
     (128, 136), (1993, E), 0.7, 0.75, ("commute", "focus"), ()),
    ("uplifting-trance", "Uplifting Trance", "electronic", ("trance",), ("epic trance", "euphoric trance"),
     (136, 142), (1996, E), 0.85, 0.9, ("uplifting", "workout"), (("festival-trance", 0.8),)),
    ("vocal-trance", "Vocal Trance", "electronic", ("trance",), (),
     (132, 140), (1998, E), 0.7, 0.85, ("uplifting", "commute"), ()),
    ("tech-trance", "Tech Trance", "electronic", ("trance", "techno"), (),
     (134, 142), (1999, E), 0.85, 0.55, ("workout", "party"), ()),
    ("psytrance", "Psytrance", "electronic", ("trance",), ("psy", "psychedelic trance", "psy trance"),
     (138, 148), (1994, E), 0.85, 0.6, ("party", "workout", "late-night"),
     (("goa-trance", 0.9), ("full-on", 0.9), ("psydub", 0.5))),
    ("goa-trance", "Goa Trance", "electronic", ("psytrance",), ("goa",),
     (135, 148), (1991, E), 0.8, 0.7, ("party", "late-night"), ()),
    ("full-on", "Full-On", "electronic", ("psytrance",), ("fullon",),
     (142, 148), (1998, E), 0.9, 0.7, ("party", "workout"), ()),
    ("dark-psytrance", "Dark Psytrance", "electronic", ("psytrance",), ("forest psy", "darkpsy"),
     (145, 160), (1999, E), 0.9, 0.25, ("late-night",), (("hi-tech-psy", 0.85),)),
    ("hi-tech-psy", "Hi-Tech Psytrance", "electronic", ("dark-psytrance",), ("hitech",),
     (170, 200), (2005, E), 0.95, 0.3, ("workout",), ()),
    ("psydub", "Psydub", "electronic", ("psytrance", "dub"), ("psybient",),
     (80, 120), (1995, E), 0.35, 0.65, ("chill", "wind-down", "focus"), (("downtempo", 0.7),)),
    ("festival-trance", "Festival Trance", "electronic", ("trance",), ("mainstage trance",),
     (132, 140), (2010, E), 0.9, 0.85, ("party", "uplifting"), ()),
    ("hard-trance", "Hard Trance", "electronic", ("trance",), (),
     (140, 150), (1994, E), 0.9, 0.6, ("workout", "party"), (("hardstyle", 0.7),)),

    # ─── Breakbeat / bass ──────────────────────────────────────────────────
    ("breakbeat", "Breakbeat", "electronic", ("electronic",), ("breaks",),
     (125, 145), (1988, E), 0.75, 0.6, ("party", "workout"), (("big-beat", 0.8), ("nu-skool-breaks", 0.85))),
    ("big-beat", "Big Beat", "electronic", ("breakbeat",), (),
     (120, 140), (1994, E), 0.85, 0.7, ("party", "workout"), ()),
    ("nu-skool-breaks", "Nu Skool Breaks", "electronic", ("breakbeat",), ("nuskool",),
     (130, 140), (1998, E), 0.8, 0.55, ("party",), ()),
    ("breakbeat-hardcore", "Breakbeat Hardcore", "electronic", ("breakbeat", "hardcore-techno"), ("oldskool", "rave"),
     (130, 155), (1990, 1994), 0.9, 0.7, ("party",), (("jungle", 0.8), ("happy-hardcore", 0.7))),
    ("uk-bass", "UK Bass", "electronic", ("electronic",), ("bass music",),
     (128, 142), (2008, E), 0.75, 0.5, ("party", "late-night"), (("uk-garage", 0.7), ("dubstep", 0.7))),
    ("uk-garage", "UK Garage", "electronic", ("garage-house",), ("ukg", "garage", "2-step"),
     (130, 138), (1995, E), 0.7, 0.7, ("party", "commute", "late-night"),
     (("speed-garage", 0.85), ("future-garage", 0.7), ("bassline", 0.8))),
    ("speed-garage", "Speed Garage", "electronic", ("uk-garage",), (),
     (135, 142), (1996, E), 0.8, 0.65, ("party",), ()),
    ("bassline", "Bassline", "electronic", ("uk-garage",), ("niche", "4x4 garage"),
     (135, 142), (2002, E), 0.8, 0.6, ("party",), ()),
    ("future-garage", "Future Garage", "electronic", ("uk-garage",), (),
     (128, 140), (2008, E), 0.45, 0.5, ("late-night", "focus", "wind-down"),
     (("ambient-dub", 0.6), ("lofi-hiphop", 0.5))),
    ("dubstep", "Dubstep", "electronic", ("uk-garage", "dub"), (),
     (138, 142), (2002, E), 0.8, 0.4, ("workout", "late-night"),
     (("brostep", 0.8), ("deep-dubstep", 0.8), ("riddim", 0.75))),
    ("deep-dubstep", "Deep Dubstep", "electronic", ("dubstep",), ("140", "meditative dubstep"),
     (138, 142), (2005, E), 0.55, 0.4, ("late-night", "focus"), (("dub-techno", 0.5),)),
    ("brostep", "Brostep", "electronic", ("dubstep",), ("filthy dubstep",),
     (138, 145), (2010, E), 0.95, 0.4, ("workout", "party"), (("riddim", 0.85),)),
    ("riddim", "Riddim", "electronic", ("dubstep",), (),
     (138, 152), (2014, E), 0.9, 0.35, ("workout",), ()),
    ("trap-edm", "EDM Trap", "electronic", ("electronic", "trap"), ("festival trap",),
     (140, 160), (2012, E), 0.85, 0.55, ("party", "workout"), (("future-bass", 0.7), ("hardwave", 0.6))),
    ("future-bass", "Future Bass", "electronic", ("trap-edm",), (),
     (130, 160), (2014, E), 0.7, 0.8, ("commute", "uplifting"), (("kawaii-future-bass", 0.8),)),
    ("kawaii-future-bass", "Kawaii Future Bass", "electronic", ("future-bass",), (),
     (140, 160), (2015, E), 0.75, 0.9, ("uplifting",), ()),
    ("hardwave", "Hardwave", "electronic", ("trap-edm", "wave"), (),
     (140, 160), (2017, E), 0.7, 0.4, ("late-night", "commute"), (("wave", 0.85),)),
    ("wave", "Wave", "electronic", ("electronic",), ("wave music",),
     (130, 150), (2015, E), 0.55, 0.4, ("late-night", "focus"), (("synthwave", 0.5),)),
    ("jersey-club", "Jersey Club", "electronic", ("breakbeat", "house"), (),
     (130, 145), (2000, E), 0.85, 0.7, ("party", "workout"), (("baltimore-club", 0.9),)),
    ("baltimore-club", "Baltimore Club", "electronic", ("house", "breakbeat"), ("bmore",),
     (128, 140), (1990, E), 0.85, 0.7, ("party",), ()),

    # ─── Jungle / drum & bass ──────────────────────────────────────────────
    ("jungle", "Jungle", "electronic", ("breakbeat-hardcore",), (),
     (155, 175), (1992, E), 0.85, 0.55, ("party", "workout"),
     (("drum-and-bass", 0.9), ("ragga-jungle", 0.85))),
    ("ragga-jungle", "Ragga Jungle", "electronic", ("jungle",), (),
     (160, 175), (1993, E), 0.85, 0.7, ("party",), (("dancehall", 0.6),)),
    ("drum-and-bass", "Drum & Bass", "electronic", ("jungle",), ("dnb", "d&b", "drum n bass", "drum'n'bass"),
     (170, 178), (1993, E), 0.85, 0.55, ("workout", "commute", "party"),
     (("jungle", 0.9),)),
    ("liquid-dnb", "Liquid Drum & Bass", "electronic", ("drum-and-bass",), ("liquid", "liquid funk"),
     (170, 176), (1996, E), 0.6, 0.8, ("commute", "focus", "uplifting"),
     (("atmospheric-dnb", 0.9), ("soulful-house", 0.4))),
    ("atmospheric-dnb", "Atmospheric Drum & Bass", "electronic", ("drum-and-bass",), ("intelligent dnb", "ambient dnb"),
     (170, 176), (1994, E), 0.5, 0.65, ("focus", "late-night", "wind-down"), ()),
    ("neurofunk", "Neurofunk", "electronic", ("drum-and-bass",), ("neuro",),
     (172, 178), (1997, E), 0.95, 0.3, ("workout",), (("techstep", 0.9), ("darkstep", 0.85))),
    ("techstep", "Techstep", "electronic", ("drum-and-bass",), (),
     (170, 178), (1995, E), 0.9, 0.3, ("workout", "late-night"), ()),
    ("darkstep", "Darkstep", "electronic", ("drum-and-bass",), (),
     (175, 185), (1998, E), 0.95, 0.2, ("workout",), ()),
    ("jump-up", "Jump Up", "electronic", ("drum-and-bass",), (),
     (172, 178), (1995, E), 0.9, 0.65, ("party", "workout"), ()),
    ("drumfunk", "Drumfunk", "electronic", ("drum-and-bass",), (),
     (170, 180), (2000, E), 0.8, 0.5, ("focus",), ()),
    ("halftime-dnb", "Halftime", "electronic", ("drum-and-bass",), ("half time dnb",),
     (85, 90), (2012, E), 0.7, 0.4, ("late-night", "focus"), (("deep-dubstep", 0.6),)),
    ("jungle-terror", "Jungle Terror", "electronic", ("jungle", "electro-house"), (),
     (128, 132), (2013, E), 0.9, 0.5, ("party",), ()),

    # ─── Hardcore ──────────────────────────────────────────────────────────
    ("hardcore-techno", "Hardcore Techno", "electronic", ("techno",), ("hardcore",),
     (160, 200), (1990, E), 0.95, 0.45, ("workout", "party"),
     (("gabber", 0.9), ("happy-hardcore", 0.7))),
    ("gabber", "Gabber", "electronic", ("hardcore-techno",), ("gabba",),
     (160, 190), (1991, E), 1.0, 0.4, ("workout",), (("hardcore-uptempo", 0.85),)),
    ("hardcore-uptempo", "Uptempo Hardcore", "electronic", ("gabber",), ("uptempo",),
     (190, 230), (2010, E), 1.0, 0.3, ("workout",), (("terrorcore", 0.9),)),
    ("terrorcore", "Terrorcore", "electronic", ("gabber",), ("terror",),
     (200, 260), (1993, E), 1.0, 0.15, ("workout",), (("speedcore", 0.9),)),
    ("speedcore", "Speedcore", "electronic", ("hardcore-techno",), (),
     (250, 400), (1993, E), 1.0, 0.2, ("workout",), ()),
    ("happy-hardcore", "Happy Hardcore", "electronic", ("hardcore-techno",), ("happycore",),
     (165, 180), (1992, E), 0.95, 0.95, ("party", "uplifting", "workout"), (("uk-hardcore", 0.9),)),
    ("uk-hardcore", "UK Hardcore", "electronic", ("happy-hardcore",), (),
     (170, 180), (2000, E), 0.95, 0.9, ("party", "uplifting"), ()),
    ("hardstyle", "Hardstyle", "electronic", ("hard-trance", "hardcore-techno"), (),
     (145, 160), (2000, E), 0.95, 0.6, ("workout", "party"),
     (("rawstyle", 0.9), ("euphoric-hardstyle", 0.85))),
    ("rawstyle", "Rawstyle", "electronic", ("hardstyle",), ("raw hardstyle",),
     (150, 165), (2010, E), 1.0, 0.35, ("workout",), ()),
    ("euphoric-hardstyle", "Euphoric Hardstyle", "electronic", ("hardstyle",), (),
     (150, 158), (2010, E), 0.9, 0.85, ("workout", "uplifting", "party"), ()),
    ("frenchcore", "Frenchcore", "electronic", ("hardcore-techno",), (),
     (190, 220), (1995, E), 1.0, 0.4, ("workout",), ()),
    ("hardtek", "Hardtek", "electronic", ("hardcore-techno",), ("tribecore",),
     (170, 190), (1995, E), 0.95, 0.45, ("workout", "party"), ()),
    ("digital-hardcore", "Digital Hardcore", "electronic", ("hardcore-techno", "industrial"), (),
     (180, 220), (1993, E), 1.0, 0.2, ("workout",), ()),

    # ─── Downtempo / chill ─────────────────────────────────────────────────
    ("downtempo", "Downtempo", "electronic", ("electronic",), ("chillout", "chill out"),
     (70, 110), (1990, E), 0.3, 0.65, ("chill", "wind-down", "focus"),
     (("trip-hop", 0.8), ("lounge", 0.8), ("ambient", 0.7))),
    ("trip-hop", "Trip-Hop", "electronic", ("downtempo", "hiphop"), ("bristol sound",),
     (80, 110), (1991, E), 0.4, 0.4, ("late-night", "chill", "wind-down"), (("lofi-hiphop", 0.6),)),
    ("lounge", "Lounge", "electronic", ("downtempo",), ("chillout lounge",),
     (70, 110), (1990, E), 0.25, 0.75, ("chill", "wind-down"), (("bossa-nova", 0.5),)),
    ("nu-jazz", "Nu Jazz", "electronic", ("downtempo", "jazz"), ("future jazz",),
     (90, 125), (1995, E), 0.45, 0.75, ("chill", "focus", "wind-down"), (("broken-beat", 0.8),)),
    ("broken-beat", "Broken Beat", "electronic", ("nu-jazz",), ("bruk",),
     (110, 130), (1997, E), 0.6, 0.7, ("focus", "commute"), ()),
    ("chillwave", "Chillwave", "electronic", ("downtempo",), ("glo-fi",),
     (90, 115), (2009, E), 0.35, 0.7, ("chill", "wind-down"), (("synthwave", 0.6), ("dream-pop", 0.6))),
    ("synthwave", "Synthwave", "electronic", ("electronic",), ("retrowave", "outrun"),
     (80, 120), (2005, E), 0.55, 0.65, ("commute", "late-night", "focus"),
     (("darksynth", 0.85), ("italo-disco", 0.6), ("vaporwave", 0.5))),
    ("darksynth", "Darksynth", "electronic", ("synthwave",), ("dark synthwave",),
     (100, 130), (2013, E), 0.8, 0.3, ("workout", "late-night"), ()),
    ("vaporwave", "Vaporwave", "electronic", ("electronic",), (),
     (60, 100), (2010, E), 0.25, 0.55, ("chill", "focus"), (("mallsoft", 0.9),)),
    ("mallsoft", "Mallsoft", "electronic", ("vaporwave",), (),
     (60, 90), (2013, E), 0.15, 0.6, ("wind-down", "focus"), ()),
    ("italo-disco", "Italo Disco", "electronic", ("disco",), (),
     (110, 125), (1977, E), 0.6, 0.8, ("party", "commute"), ()),

    # ─── Phonk & club rap crossovers ───────────────────────────────────────
    ("phonk", "Phonk", "electronic", ("hiphop", "electronic"), (),
     (130, 160), (2010, E), 0.75, 0.35, ("workout", "late-night", "commute"),
     (("drift-phonk", 0.9), ("memphis-rap", 0.8))),
    ("drift-phonk", "Drift Phonk", "electronic", ("phonk",), ("driftphonk",),
     (140, 160), (2019, E), 0.9, 0.3, ("workout", "commute"), (("phonk-brazilian", 0.8),)),
    ("phonk-brazilian", "Brazilian Phonk", "electronic", ("phonk", "baile-funk"), ("funk phonk",),
     (130, 150), (2022, E), 0.9, 0.45, ("workout", "party"), ()),
    ("hyperpop", "Hyperpop", "electronic", ("pop", "electronic"), (),
     (140, 170), (2014, E), 0.85, 0.7, ("party", "uplifting"),
     (("digicore", 0.9), ("glitchcore", 0.85), ("bubblegum-bass", 0.9))),
    ("bubblegum-bass", "Bubblegum Bass", "electronic", ("hyperpop",), ("pc music",),
     (130, 160), (2013, E), 0.8, 0.85, ("party", "uplifting"), ()),
    ("digicore", "Digicore", "electronic", ("hyperpop",), (),
     (140, 170), (2019, E), 0.8, 0.6, ("party",), ()),
    ("glitchcore", "Glitchcore", "electronic", ("hyperpop",), (),
     (150, 180), (2019, E), 0.9, 0.5, ("workout",), ()),

    # ─── IDM / experimental electronic ─────────────────────────────────────
    ("idm", "IDM", "electronic", ("electronic",), ("intelligent dance music", "braindance"),
     (80, 160), (1992, E), 0.5, 0.5, ("focus",), (("glitch", 0.8), ("breakcore", 0.6), ("ambient", 0.6))),
    ("glitch", "Glitch", "electronic", ("idm",), (),
     (80, 140), (1994, E), 0.5, 0.45, ("focus",), ()),
    ("breakcore", "Breakcore", "electronic", ("idm", "hardcore-techno"), (),
     (160, 220), (1996, E), 0.95, 0.35, ("workout",), (("drumfunk", 0.6),)),
    ("footwork", "Footwork", "electronic", ("electronic",), ("foot work",),
     (155, 165), (2005, E), 0.8, 0.55, ("workout", "party"), (("drum-and-bass", 0.5),)),
    ("ambient-dub", "Ambient Dub", "electronic", ("ambient", "dub"), (),
     (60, 100), (1990, E), 0.25, 0.6, ("wind-down", "focus", "late-night"), ()),
    ("dub", "Dub", "electronic", ("reggae",), (),
     (60, 90), (1968, E), 0.4, 0.6, ("chill", "late-night", "wind-down"), (("dub-techno", 0.6),)),

    # ─── Electronic · further coverage ─────────────────────────────────────
    ("balearic", "Balearic Beat", "electronic", ("house",), ("balearic house",),
     (100, 122), (1985, E), 0.45, 0.85, ("chill", "commute", "wind-down"),
     (("nu-disco", 0.7), ("organic-house", 0.7))),
    ("lo-fi-house", "Lo-fi House", "electronic", ("house",), ("outsider house",),
     (118, 128), (2014, E), 0.5, 0.6, ("chill", "late-night"), (("microhouse", 0.6),)),
    ("disco-house", "Disco House", "electronic", ("house", "disco"), (),
     (120, 128), (1994, E), 0.7, 0.85, ("party",), (("french-house", 0.8),)),
    ("hard-house", "Hard House", "electronic", ("house",), ("uk hard house",),
     (140, 152), (1992, E), 0.9, 0.6, ("workout", "party"), (("hard-trance", 0.8),)),
    ("ghetto-house", "Ghetto House", "electronic", ("chicago-house",), ("booty house",),
     (130, 145), (1992, E), 0.85, 0.6, ("party",), (("footwork", 0.8), ("juke", 0.85))),
    ("juke", "Juke", "electronic", ("ghetto-house",), ("chicago juke",),
     (150, 165), (1995, E), 0.85, 0.55, ("party", "workout"), (("footwork", 0.9),)),
    ("kuduro", "Kuduro", "electronic", ("global",), (),
     (135, 145), (1989, E), 0.9, 0.75, ("party", "workout"), (("gqom", 0.5), ("baile-funk", 0.6))),
    ("moombahton", "Moombahton", "electronic", ("house", "reggaeton"), (),
     (108, 112), (2009, E), 0.8, 0.7, ("party",), ()),
    ("tropical-house", "Tropical House", "electronic", ("deep-house",), ("trop house",),
     (100, 118), (2013, E), 0.5, 0.85, ("chill", "commute"), (("balearic", 0.7),)),
    ("progressive-breaks", "Progressive Breaks", "electronic", ("breakbeat", "progressive-house"), (),
     (128, 136), (1998, E), 0.7, 0.65, ("commute", "party"), ()),
    ("florida-breaks", "Florida Breaks", "electronic", ("breakbeat",), ("funky breaks",),
     (128, 138), (1995, E), 0.8, 0.7, ("party",), ()),
    ("glitch-hop", "Glitch Hop", "electronic", ("glitch", "hiphop"), (),
     (100, 115), (2004, E), 0.7, 0.6, ("party", "focus"), (("neurofunk", 0.5),)),
    ("neurohop", "Neurohop", "electronic", ("glitch-hop", "neurofunk"), (),
     (100, 115), (2010, E), 0.8, 0.4, ("workout", "focus"), ()),
    ("colour-bass", "Colour Bass", "electronic", ("future-bass",), ("color bass",),
     (140, 160), (2018, E), 0.8, 0.85, ("uplifting", "party"), ()),
    ("melodic-dubstep", "Melodic Dubstep", "electronic", ("dubstep",), (),
     (140, 150), (2011, E), 0.7, 0.7, ("commute", "uplifting"), (("future-bass", 0.75),)),
    ("tearout", "Tearout", "electronic", ("brostep",), (),
     (140, 150), (2015, E), 0.95, 0.35, ("workout",), ()),
    ("dungeon-sound", "Dungeon Sound", "electronic", ("riddim",), (),
     (140, 150), (2018, E), 0.9, 0.25, ("workout", "late-night"), ()),
    ("uk-funky", "UK Funky", "electronic", ("uk-garage",), ("funky",),
     (128, 136), (2008, E), 0.7, 0.75, ("party",), (("afro-house", 0.7),)),
    ("garage-revival", "Garage Revival", "electronic", ("uk-garage",), ("new garage",),
     (130, 140), (2020, E), 0.7, 0.7, ("party", "commute"), ()),
    ("witch-house", "Witch House", "electronic", ("electronic",), (),
     (60, 100), (2009, E), 0.4, 0.15, ("late-night",), (("dark-ambient", 0.6), ("phonk", 0.5))),
    ("darkwave", "Darkwave", "electronic", ("post-punk", "electronic"), (),
     (90, 130), (1983, E), 0.55, 0.25, ("late-night",), (("goth-rock", 0.8), ("coldwave", 0.85))),
    ("coldwave", "Coldwave", "electronic", ("post-punk",), (),
     (100, 135), (1978, E), 0.6, 0.25, ("late-night", "commute"), ()),
    ("minimal-wave", "Minimal Wave", "electronic", ("coldwave", "synthpop"), (),
     (100, 130), (1980, E), 0.55, 0.4, ("late-night", "focus"), ()),
    ("chiptune", "Chiptune", "electronic", ("electronic",), ("8-bit", "8bit", "bitpop"),
     (120, 180), (1985, E), 0.75, 0.85, ("focus", "workout"), (("breakcore", 0.5),)),
    ("nightcore", "Nightcore", "electronic", ("happy-hardcore",), (),
     (160, 180), (2002, E), 0.9, 0.85, ("workout", "uplifting"), ()),
    ("speed-house", "Speed House", "electronic", ("hard-house", "gabber"), (),
     (145, 160), (2015, E), 0.95, 0.55, ("workout",), ()),
    ("psystyle", "Psystyle", "electronic", ("hardstyle", "psytrance"), (),
     (150, 160), (2015, E), 0.95, 0.6, ("workout", "party"), ()),
    ("hardcore-frenchcore", "Uptempo Frenchcore", "electronic", ("frenchcore",), (),
     (200, 230), (2015, E), 1.0, 0.35, ("workout",), ()),
    ("makina", "Makina", "electronic", ("hard-trance",), (),
     (160, 180), (1990, E), 0.95, 0.7, ("workout", "party"), ()),
    ("eurodance", "Eurodance", "electronic", ("house", "pop"), (),
     (135, 145), (1990, E), 0.85, 0.9, ("party", "uplifting"), (("eurobeat", 0.85),)),
    ("eurobeat", "Eurobeat", "electronic", ("eurodance",), ("hi-nrg eurobeat",),
     (150, 165), (1985, E), 0.9, 0.9, ("workout", "party"), ()),
    ("hi-nrg", "Hi-NRG", "electronic", ("disco",), ("hinrg",),
     (125, 135), (1977, E), 0.85, 0.85, ("party", "workout"), (("italo-disco", 0.8),)),
    ("freestyle", "Freestyle", "electronic", ("electro", "hi-nrg"), ("latin freestyle",),
     (110, 125), (1983, E), 0.75, 0.8, ("party",), ()),
    ("new-beat", "New Beat", "electronic", ("ebm", "acid-house"), (),
     (100, 115), (1987, 1991), 0.7, 0.45, ("late-night",), ()),
    ("bleep-techno", "Bleep Techno", "electronic", ("detroit-techno",), ("bleep",),
     (120, 132), (1988, E), 0.7, 0.55, ("focus",), ()),
    ("illbient", "Illbient", "electronic", ("ambient", "trip-hop"), (),
     (70, 100), (1994, E), 0.4, 0.3, ("late-night", "focus"), ()),
    ("trance-goa-psybreaks", "Psybreaks", "electronic", ("breakbeat", "psytrance"), (),
     (130, 145), (1998, E), 0.8, 0.6, ("party", "workout"), ()),
    ("electro-swing", "Electro Swing", "electronic", ("electronic", "swing"), (),
     (110, 130), (2000, E), 0.75, 0.9, ("party",), ()),
    ("future-funk", "Future Funk", "electronic", ("vaporwave", "nu-disco"), (),
     (110, 130), (2013, E), 0.7, 0.9, ("party", "commute"), (("city-pop", 0.75),)),
    ("barber-beats", "Barber Beats", "electronic", ("vaporwave", "lofi-hiphop"), (),
     (60, 90), (2016, E), 0.2, 0.6, ("wind-down", "sleep", "focus"), ()),
    ("slushwave", "Slushwave", "electronic", ("vaporwave", "ambient"), (),
     (40, 70), (2015, E), 0.15, 0.55, ("sleep", "wind-down"), ()),
    ("hardvapour", "Hardvapour", "electronic", ("vaporwave", "hard-techno"), (),
     (140, 170), (2015, E), 0.85, 0.3, ("workout",), ()),
    ("deconstructed-club", "Deconstructed Club", "electronic", ("electronic",), ("post-club",),
     (120, 160), (2012, E), 0.75, 0.35, ("late-night", "party"), (("hyperpop", 0.6), ("industrial-techno", 0.5))),
    ("footwork-jungle", "Jungle Footwork", "electronic", ("footwork", "jungle"), (),
     (160, 175), (2012, E), 0.85, 0.5, ("workout",), ()),
    ("ambient-house", "Ambient House", "electronic", ("house", "ambient"), (),
     (110, 125), (1989, E), 0.35, 0.7, ("chill", "wind-down", "focus"), (("balearic", 0.6),)),
    ("acid-jazz", "Acid Jazz", "electronic", ("jazz", "funk"), (),
     (100, 125), (1987, E), 0.6, 0.8, ("chill", "commute"), (("nu-jazz", 0.8), ("broken-beat", 0.7))),
    ("turntablism", "Turntablism", "hiphop", ("hiphop",), ("scratch",),
     (85, 110), (1975, E), 0.7, 0.6, ("focus",), (("abstract-hiphop", 0.7),)),
    ("boogie", "Boogie", "soul", ("funk", "disco"), ("post-disco",),
     (105, 120), (1978, E), 0.65, 0.85, ("party", "commute"), (("nu-disco", 0.75),)),
    ("northern-soul", "Northern Soul", "soul", ("soul",), (),
     (110, 135), (1968, E), 0.75, 0.85, ("party", "commute"), (("motown", 0.8),)),
    ("hardcore-continuum", "Hardcore Continuum", "electronic", ("breakbeat-hardcore",), (),
     (130, 175), (1990, E), 0.8, 0.55, ("party",), (("uk-garage", 0.6), ("grime", 0.6))),
    ("wonky", "Wonky", "electronic", ("glitch-hop", "hiphop"), (),
     (85, 110), (2008, E), 0.5, 0.55, ("focus", "chill"), (("abstract-hiphop", 0.7),)),
    ("beatless", "Beatless", "experimental", ("ambient",), (),
     (0, 0), (1970, E), 0.1, 0.55, ("sleep", "focus", "wind-down"), ()),
    ("space-ambient", "Space Ambient", "experimental", ("ambient",), ("space music",),
     (0, 0), (1970, E), 0.15, 0.6, ("sleep", "focus"), (("berlin-school", 0.8),)),
    ("berlin-school", "Berlin School", "experimental", ("ambient", "krautrock"), (),
     (90, 130), (1970, E), 0.4, 0.6, ("focus", "commute"), ()),
    ("power-electronics", "Power Electronics", "experimental", ("noise",), (),
     (0, 0), (1980, E), 0.95, 0.1, (), ()),
    ("plunderphonics", "Plunderphonics", "experimental", ("musique-concrete",), (),
     (0, 0), (1985, E), 0.5, 0.5, ("focus",), (("vaporwave", 0.5),)),

    # ─── Coverage fill ─────────────────────────────────────────────────────
    ("dark-disco", "Dark Disco", "electronic", ("nu-disco", "ebm"), (),
     (115, 125), (2015, E), 0.65, 0.35, ("late-night",), (("italo-disco", 0.6),)),
    ("indie-dance", "Indie Dance", "electronic", ("nu-disco", "indie-rock"), (),
     (115, 125), (2005, E), 0.6, 0.65, ("late-night", "party"), (("dark-disco", 0.8),)),
    ("raw-trance", "Raw Trance", "electronic", ("trance", "hard-techno"), (),
     (140, 150), (2022, E), 0.9, 0.45, ("workout", "party"), (("hard-trance", 0.8),)),
    ("hypnotic-techno", "Hypnotic Techno", "electronic", ("minimal-techno",), (),
     (130, 140), (2010, E), 0.7, 0.4, ("focus", "late-night"), (("dub-techno", 0.7),)),
    ("broken-techno", "Broken Techno", "electronic", ("techno", "breakbeat"), (),
     (125, 140), (2015, E), 0.7, 0.45, ("late-night", "focus"), ()),
    ("electronica", "Electronica", "electronic", ("electronic",), ("downtempo electronica",),
     (90, 140), (1990, E), 0.5, 0.6, ("focus", "chill", "commute"), (("idm", 0.7), ("downtempo", 0.7))),
    ("trip-hop-instrumental", "Instrumental Hip-Hop", "hiphop", ("hiphop",), ("beat tape", "instrumental beats"),
     (75, 100), (1990, E), 0.4, 0.6, ("focus", "chill"), (("lofi-hiphop", 0.85), ("wonky", 0.7))),
    ("plugg", "Plugg", "hiphop", ("trap",), (),
     (120, 145), (2016, E), 0.5, 0.6, ("chill", "late-night"), (("cloud-rap", 0.8),)),
    ("rage", "Rage", "hiphop", ("trap",), ("rage beat",),
     (140, 165), (2020, E), 0.9, 0.5, ("workout", "party"), (("hyperpop", 0.6),)),
    ("jerk", "Jerk", "hiphop", ("hiphop",), ("jerk rap",),
     (130, 150), (2008, E), 0.8, 0.7, ("party",), ()),
    ("hyphy", "Hyphy", "hiphop", ("hiphop",), (),
     (100, 120), (2002, E), 0.85, 0.7, ("party", "workout"), ()),
    ("crunk", "Crunk", "hiphop", ("hiphop",), (),
     (130, 150), (1995, E), 0.9, 0.6, ("party", "workout"), (("trap", 0.7),)),
    ("chopped-and-screwed", "Chopped and Screwed", "hiphop", ("hiphop",), ("screwed", "slowed"),
     (60, 75), (1990, E), 0.3, 0.35, ("late-night", "chill"), (("phonk", 0.8), ("vaporwave", 0.5))),
    ("afroswing", "Afroswing", "global", ("afrobeats", "uk-drill"), (),
     (100, 110), (2015, E), 0.65, 0.7, ("party", "commute"), ()),
    ("amapiano-tech", "Private School Amapiano", "electronic", ("amapiano",), (),
     (110, 118), (2019, E), 0.45, 0.75, ("chill", "late-night"), (("jazz-house", 0.6),)),
    ("singeli", "Singeli", "global", ("global",), (),
     (180, 300), (2010, E), 0.95, 0.7, ("workout", "party"), (("footwork", 0.5),)),
    ("shangaan-electro", "Shangaan Electro", "global", ("global", "electronic"), (),
     (180, 190), (2005, E), 0.9, 0.85, ("party",), ()),
    ("coupe-decale", "Coupé-Décalé", "global", ("global",), (),
     (105, 120), (2002, E), 0.8, 0.85, ("party",), (("kuduro", 0.7),)),
    ("mahraganat", "Mahraganat", "global", ("global",), ("electro shaabi",),
     (110, 130), (2005, E), 0.85, 0.7, ("party",), ()),
    ("dabke", "Dabke", "global", ("global",), (),
     (110, 140), (1950, E), 0.8, 0.8, ("party",), ()),
    ("enka", "Enka", "global", ("global",), (),
     (60, 100), (1950, E), 0.35, 0.4, ("wind-down",), ()),
    ("gamelan", "Gamelan", "global", ("global",), (),
     (0, 0), (1000, E), 0.4, 0.65, ("focus",), ()),
    ("mbalax", "Mbalax", "global", ("global",), (),
     (110, 140), (1970, E), 0.8, 0.8, ("party",), ()),
    ("zouk", "Zouk", "global", ("global",), (),
     (95, 125), (1980, E), 0.6, 0.85, ("party", "chill"), (("kompa", 0.85),)),
    ("kompa", "Kompa", "global", ("global",), ("compas",),
     (95, 120), (1955, E), 0.6, 0.85, ("chill", "party"), ()),
    ("soca", "Soca", "global", ("global",), (),
     (125, 160), (1970, E), 0.9, 0.9, ("party", "workout"), (("dancehall", 0.7),)),
    ("bhangra", "Bhangra", "global", ("global",), (),
     (130, 150), (1980, E), 0.85, 0.85, ("party", "workout"), ()),
    ("post-hardcore", "Post-Hardcore", "rock", ("hardcore-punk",), (),
     (140, 180), (1985, E), 0.85, 0.4, ("workout",), (("emo", 0.75),)),
    ("noise-rock", "Noise Rock", "rock", ("rock", "noise"), (),
     (110, 170), (1980, E), 0.85, 0.3, ("workout",), ()),
    ("slowcore", "Slowcore", "rock", ("indie-rock",), ("sadcore",),
     (50, 90), (1990, E), 0.2, 0.25, ("wind-down", "late-night"), (("dream-pop", 0.6),)),
    ("midwest-emo", "Midwest Emo", "rock", ("emo", "math-rock"), (),
     (110, 160), (1994, E), 0.6, 0.45, ("commute",), ()),
    ("surf-rock", "Surf Rock", "rock", ("rock",), (),
     (120, 170), (1960, E), 0.75, 0.8, ("commute", "party"), ()),
    ("space-rock", "Space Rock", "rock", ("psychedelic-rock",), (),
     (90, 140), (1968, E), 0.55, 0.5, ("focus", "commute"), (("krautrock", 0.8),)),
    ("symphonic-metal", "Symphonic Metal", "metal", ("metal", "classical"), (),
     (110, 170), (1996, E), 0.85, 0.6, ("workout",), (("power-metal", 0.8),)),
    ("technical-death-metal", "Technical Death Metal", "metal", ("death-metal",), ("tech death",),
     (180, 260), (1991, E), 1.0, 0.25, ("workout", "focus"), (("progressive-metal", 0.7),)),
    ("blackgaze", "Blackgaze", "metal", ("atmospheric-black-metal", "shoegaze"), (),
     (120, 190), (2008, E), 0.75, 0.35, ("focus", "late-night"), ()),
    ("funeral-doom", "Funeral Doom", "metal", ("doom-metal",), (),
     (40, 70), (1991, E), 0.4, 0.1, ("late-night", "focus"), (("drone", 0.7),)),
    ("mathcore", "Mathcore", "metal", ("metalcore", "math-rock"), (),
     (150, 250), (1993, E), 1.0, 0.3, ("workout",), ()),
    ("hard-bop-soul-jazz", "Soul Jazz", "jazz", ("hard-bop", "soul"), (),
     (100, 160), (1957, E), 0.6, 0.8, ("chill", "commute"), (("acid-jazz", 0.75),)),
    ("gypsy-jazz", "Gypsy Jazz", "jazz", ("jazz",), ("manouche",),
     (140, 220), (1934, E), 0.7, 0.85, ("party", "commute"), ()),
    ("vocal-jazz", "Vocal Jazz", "jazz", ("jazz",), ("jazz vocal",),
     (70, 140), (1930, E), 0.4, 0.75, ("wind-down", "chill"), (("swing", 0.7),)),
    ("chamber-music", "Chamber Music", "classical", ("classical",), (),
     (0, 0), (1700, E), 0.35, 0.7, ("focus", "wind-down"), ()),
    ("choral", "Choral", "classical", ("classical",), (),
     (0, 0), (1400, E), 0.4, 0.75, ("focus", "wind-down"), (("gospel", 0.5),)),
    ("early-music", "Early Music", "classical", ("classical",), ("medieval", "renaissance"),
     (0, 0), (1100, 1600), 0.35, 0.65, ("focus",), ()),
    ("outlaw-country", "Outlaw Country", "folk", ("country",), (),
     (95, 140), (1970, E), 0.6, 0.6, ("commute",), (("americana", 0.8),)),
    ("honky-tonk", "Honky Tonk", "folk", ("country",), (),
     (110, 160), (1940, E), 0.7, 0.7, ("party", "commute"), ()),
    ("freak-folk", "Freak Folk", "folk", ("folk", "psychedelic-rock"), (),
     (80, 130), (1998, E), 0.45, 0.6, ("chill", "focus"), ()),

    # ─── Ambient & experimental ────────────────────────────────────────────
    ("ambient", "Ambient", "experimental", (), (),
     (40, 90), (1970, E), 0.15, 0.6, ("focus", "wind-down", "sleep"),
     (("drone", 0.8), ("new-age", 0.7), ("dark-ambient", 0.7))),
    ("dark-ambient", "Dark Ambient", "experimental", ("ambient",), (),
     (40, 80), (1980, E), 0.2, 0.15, ("late-night", "focus"), (("drone", 0.8),)),
    ("drone", "Drone", "experimental", ("ambient",), (),
     (40, 70), (1960, E), 0.15, 0.4, ("focus", "sleep"), ()),
    ("new-age", "New Age", "experimental", ("ambient",), (),
     (50, 90), (1975, E), 0.15, 0.8, ("wind-down", "sleep"), ()),
    ("noise", "Noise", "experimental", (), (),
     (0, 0), (1970, E), 0.9, 0.15, (), (("industrial", 0.7), ("harsh-noise-wall", 0.9))),
    ("harsh-noise-wall", "Harsh Noise Wall", "experimental", ("noise",), ("hnw",),
     (0, 0), (2000, E), 0.7, 0.1, (), ()),
    ("industrial", "Industrial", "experimental", (), (),
     (100, 140), (1975, E), 0.8, 0.2, ("workout", "late-night"), (("ebm", 0.7), ("industrial-metal", 0.7))),
    ("musique-concrete", "Musique Concrète", "experimental", (), (),
     (0, 0), (1948, E), 0.4, 0.35, (), (("modern-classical", 0.5),)),
    ("field-recording", "Field Recording", "experimental", ("ambient",), (),
     (0, 0), (1950, E), 0.1, 0.55, ("sleep", "focus"), ()),
    ("lowercase", "Lowercase", "experimental", ("ambient",), (),
     (0, 0), (1990, E), 0.1, 0.5, ("focus", "sleep"), ()),

    # ─── Hip-hop ───────────────────────────────────────────────────────────
    ("hiphop", "Hip-Hop", "hiphop", (), ("rap", "hip hop"),
     (80, 100), (1973, E), 0.7, 0.6, ("commute", "party", "workout"), ()),
    ("boom-bap", "Boom Bap", "hiphop", ("hiphop",), ("90s hip hop", "golden age"),
     (85, 100), (1988, E), 0.6, 0.6, ("commute", "focus"), (("jazz-rap", 0.85),)),
    ("jazz-rap", "Jazz Rap", "hiphop", ("boom-bap", "jazz"), (),
     (85, 100), (1988, E), 0.5, 0.75, ("chill", "focus", "commute"), (("lofi-hiphop", 0.8),)),
    ("lofi-hiphop", "Lo-fi Hip-Hop", "hiphop", ("jazz-rap", "downtempo"), ("lofi", "lo-fi beats", "chillhop"),
     (70, 90), (2010, E), 0.25, 0.65, ("focus", "chill", "wind-down", "sleep"), ()),
    ("trap", "Trap", "hiphop", ("hiphop",), (),
     (130, 160), (2000, E), 0.75, 0.45, ("workout", "party", "commute"),
     (("drill", 0.8), ("mumble-rap", 0.7))),
    ("drill", "Drill", "hiphop", ("trap",), (),
     (135, 145), (2010, E), 0.8, 0.25, ("workout", "late-night"), (("uk-drill", 0.9),)),
    ("uk-drill", "UK Drill", "hiphop", ("drill",), (),
     (138, 145), (2012, E), 0.8, 0.25, ("workout", "late-night"), ()),
    ("memphis-rap", "Memphis Rap", "hiphop", ("hiphop",), ("horrorcore memphis",),
     (130, 150), (1990, E), 0.7, 0.3, ("late-night", "workout"), ()),
    ("cloud-rap", "Cloud Rap", "hiphop", ("trap",), (),
     (120, 145), (2010, E), 0.5, 0.5, ("late-night", "chill"), (("emo-rap", 0.8),)),
    ("emo-rap", "Emo Rap", "hiphop", ("cloud-rap",), (),
     (130, 155), (2015, E), 0.6, 0.3, ("late-night",), ()),
    ("mumble-rap", "Mumble Rap", "hiphop", ("trap",), (),
     (130, 150), (2013, E), 0.65, 0.5, ("party", "commute"), ()),
    ("g-funk", "G-Funk", "hiphop", ("hiphop", "funk"), ("west coast rap",),
     (90, 100), (1992, E), 0.6, 0.75, ("commute", "chill", "party"), ()),
    ("conscious-hiphop", "Conscious Hip-Hop", "hiphop", ("hiphop",), (),
     (85, 100), (1988, E), 0.6, 0.55, ("commute", "focus"), (("boom-bap", 0.8),)),
    ("grime", "Grime", "hiphop", ("uk-garage", "hiphop"), (),
     (138, 142), (2002, E), 0.85, 0.4, ("workout", "party"), (("uk-drill", 0.7),)),
    ("abstract-hiphop", "Abstract Hip-Hop", "hiphop", ("hiphop",), ("experimental hip hop",),
     (80, 100), (1990, E), 0.55, 0.5, ("focus",), (("trip-hop", 0.7), ("idm", 0.5))),
    ("afrobeats", "Afrobeats", "global", ("global",), ("afropop",),
     (100, 115), (2000, E), 0.6, 0.85, ("party", "commute", "chill"),
     (("amapiano", 0.6), ("dancehall", 0.6))),

    # ─── Rock ──────────────────────────────────────────────────────────────
    ("rock", "Rock", "rock", (), (),
     (100, 140), (1955, E), 0.7, 0.6, ("commute", "workout", "party"), ()),
    ("classic-rock", "Classic Rock", "rock", ("rock",), (),
     (100, 140), (1965, 1985), 0.7, 0.65, ("commute", "party"), ()),
    ("psychedelic-rock", "Psychedelic Rock", "rock", ("rock",), ("psych rock",),
     (90, 130), (1965, E), 0.6, 0.6, ("commute", "chill"), (("krautrock", 0.7), ("stoner-rock", 0.7))),
    ("krautrock", "Krautrock", "rock", ("psychedelic-rock",), (),
     (100, 140), (1968, E), 0.6, 0.55, ("focus", "commute"), (("ambient", 0.5),)),
    ("progressive-rock", "Progressive Rock", "rock", ("rock",), ("prog rock", "prog"),
     (90, 150), (1967, E), 0.65, 0.6, ("focus", "commute"), ()),
    ("punk", "Punk", "rock", ("rock",), ("punk rock",),
     (150, 200), (1974, E), 0.9, 0.5, ("workout", "party"), (("hardcore-punk", 0.9), ("post-punk", 0.7))),
    ("hardcore-punk", "Hardcore Punk", "rock", ("punk",), (),
     (160, 220), (1978, E), 0.95, 0.4, ("workout",), (("metalcore", 0.7),)),
    ("post-punk", "Post-Punk", "rock", ("punk",), (),
     (110, 150), (1978, E), 0.65, 0.35, ("late-night", "commute"), (("goth-rock", 0.85), ("new-wave", 0.7))),
    ("goth-rock", "Gothic Rock", "rock", ("post-punk",), ("goth",),
     (100, 140), (1979, E), 0.6, 0.25, ("late-night",), ()),
    ("new-wave", "New Wave", "rock", ("post-punk", "pop"), (),
     (110, 150), (1977, E), 0.7, 0.7, ("party", "commute"), (("synthpop", 0.85),)),
    ("indie-rock", "Indie Rock", "rock", ("rock",), ("indie",),
     (100, 150), (1980, E), 0.6, 0.65, ("commute", "chill"), (("shoegaze", 0.6), ("dream-pop", 0.6))),
    ("shoegaze", "Shoegaze", "rock", ("indie-rock",), (),
     (100, 140), (1988, E), 0.5, 0.5, ("chill", "wind-down", "focus"), (("dream-pop", 0.85),)),
    ("dream-pop", "Dream Pop", "rock", ("indie-rock",), (),
     (90, 130), (1985, E), 0.4, 0.7, ("chill", "wind-down"), ()),
    ("math-rock", "Math Rock", "rock", ("rock",), (),
     (120, 180), (1990, E), 0.7, 0.55, ("focus",), (("post-rock", 0.7),)),
    ("post-rock", "Post-Rock", "rock", ("rock",), (),
     (80, 140), (1991, E), 0.45, 0.5, ("focus", "wind-down"), (("ambient", 0.6),)),
    ("stoner-rock", "Stoner Rock", "rock", ("rock", "metal"), (),
     (90, 130), (1990, E), 0.7, 0.5, ("commute", "workout"), (("doom-metal", 0.8),)),
    ("garage-rock", "Garage Rock", "rock", ("rock",), (),
     (120, 170), (1963, E), 0.8, 0.6, ("party", "workout"), ()),
    ("grunge", "Grunge", "rock", ("rock", "punk"), (),
     (100, 150), (1988, E), 0.8, 0.35, ("workout", "commute"), ()),
    ("emo", "Emo", "rock", ("punk",), (),
     (120, 170), (1985, E), 0.7, 0.35, ("commute",), (("emo-rap", 0.5),)),
    ("britpop", "Britpop", "rock", ("indie-rock", "pop"), (),
     (110, 150), (1992, 2000), 0.7, 0.75, ("party", "commute"), ()),

    # ─── Metal ─────────────────────────────────────────────────────────────
    ("metal", "Metal", "metal", (), ("heavy metal",),
     (120, 180), (1968, E), 0.85, 0.4, ("workout",), ()),
    ("thrash-metal", "Thrash Metal", "metal", ("metal",), ("thrash",),
     (160, 220), (1981, E), 0.95, 0.35, ("workout",), (("death-metal", 0.85),)),
    ("death-metal", "Death Metal", "metal", ("thrash-metal",), (),
     (170, 250), (1983, E), 1.0, 0.2, ("workout",), (("black-metal", 0.7), ("grindcore", 0.85))),
    ("black-metal", "Black Metal", "metal", ("metal",), (),
     (150, 250), (1982, E), 0.95, 0.15, ("workout", "late-night"), (("atmospheric-black-metal", 0.9),)),
    ("atmospheric-black-metal", "Atmospheric Black Metal", "metal", ("black-metal",), (),
     (120, 200), (1994, E), 0.7, 0.25, ("focus", "late-night"), (("post-metal", 0.7),)),
    ("doom-metal", "Doom Metal", "metal", ("metal",), (),
     (60, 100), (1970, E), 0.6, 0.2, ("late-night", "focus"), (("sludge-metal", 0.85), ("drone", 0.5))),
    ("sludge-metal", "Sludge Metal", "metal", ("doom-metal", "hardcore-punk"), (),
     (70, 120), (1988, E), 0.8, 0.2, ("workout",), ()),
    ("post-metal", "Post-Metal", "metal", ("metal", "post-rock"), (),
     (80, 130), (1995, E), 0.6, 0.35, ("focus",), ()),
    ("power-metal", "Power Metal", "metal", ("metal",), (),
     (140, 200), (1983, E), 0.9, 0.8, ("workout", "uplifting"), ()),
    ("progressive-metal", "Progressive Metal", "metal", ("metal", "progressive-rock"), ("prog metal",),
     (100, 180), (1985, E), 0.8, 0.5, ("focus", "workout"), (("djent", 0.85),)),
    ("djent", "Djent", "metal", ("progressive-metal",), (),
     (100, 160), (2005, E), 0.85, 0.4, ("workout", "focus"), ()),
    ("metalcore", "Metalcore", "metal", ("hardcore-punk", "metal"), (),
     (140, 200), (1990, E), 0.95, 0.4, ("workout",), (("deathcore", 0.85),)),
    ("deathcore", "Deathcore", "metal", ("metalcore", "death-metal"), (),
     (150, 220), (2003, E), 1.0, 0.2, ("workout",), ()),
    ("grindcore", "Grindcore", "metal", ("death-metal", "hardcore-punk"), (),
     (200, 300), (1985, E), 1.0, 0.2, ("workout",), ()),
    ("nu-metal", "Nu Metal", "metal", ("metal", "hiphop"), (),
     (90, 140), (1994, E), 0.85, 0.4, ("workout",), ()),
    ("industrial-metal", "Industrial Metal", "metal", ("metal", "industrial"), (),
     (110, 150), (1988, E), 0.9, 0.25, ("workout",), ()),
    ("folk-metal", "Folk Metal", "metal", ("metal", "folk"), (),
     (120, 180), (1990, E), 0.85, 0.6, ("workout", "party"), ()),

    # ─── Pop ───────────────────────────────────────────────────────────────
    ("pop", "Pop", "pop", (), (),
     (100, 130), (1950, E), 0.65, 0.8, ("party", "commute"), ()),
    ("synthpop", "Synth-Pop", "pop", ("pop", "electronic"), ("synth pop",),
     (110, 130), (1978, E), 0.65, 0.75, ("commute", "party"), (("new-wave", 0.85), ("synthwave", 0.6))),
    ("dance-pop", "Dance-Pop", "pop", ("pop", "house"), (),
     (115, 130), (1982, E), 0.8, 0.85, ("party", "workout"), ()),
    ("electropop", "Electropop", "pop", ("pop", "electronic"), (),
     (110, 130), (1980, E), 0.7, 0.8, ("party", "commute"), ()),
    ("indie-pop", "Indie Pop", "pop", ("pop", "indie-rock"), (),
     (100, 140), (1980, E), 0.55, 0.75, ("chill", "commute"), ()),
    ("bedroom-pop", "Bedroom Pop", "pop", ("indie-pop",), (),
     (80, 120), (2014, E), 0.35, 0.65, ("chill", "wind-down"), (("lofi-hiphop", 0.6),)),
    ("k-pop", "K-Pop", "pop", ("pop",), (),
     (100, 140), (1992, E), 0.8, 0.85, ("party", "workout"), (("j-pop", 0.7),)),
    ("j-pop", "J-Pop", "pop", ("pop",), (),
     (100, 145), (1980, E), 0.75, 0.85, ("party", "commute"), ()),
    ("city-pop", "City Pop", "pop", ("pop",), (),
     (95, 125), (1975, 1990), 0.55, 0.85, ("commute", "chill"), (("vaporwave", 0.6), ("disco", 0.6))),
    ("art-pop", "Art Pop", "pop", ("pop",), (),
     (90, 130), (1965, E), 0.5, 0.6, ("focus", "chill"), ()),

    # ─── Soul, funk, disco, R&B ────────────────────────────────────────────
    ("soul", "Soul", "soul", (), (),
     (80, 120), (1958, E), 0.55, 0.8, ("chill", "commute"), (("funk", 0.8), ("motown", 0.85))),
    ("motown", "Motown", "soul", ("soul",), (),
     (100, 130), (1959, 1975), 0.65, 0.9, ("party", "commute"), ()),
    ("funk", "Funk", "soul", ("soul",), (),
     (95, 120), (1965, E), 0.75, 0.85, ("party", "workout"), (("disco", 0.8), ("g-funk", 0.6))),
    ("disco", "Disco", "soul", ("funk",), (),
     (110, 130), (1972, E), 0.75, 0.9, ("party",), (("nu-disco", 0.85), ("italo-disco", 0.7))),
    ("rnb", "R&B", "soul", ("soul",), ("r and b", "rhythm and blues", "randb"),
     (70, 110), (1985, E), 0.5, 0.75, ("chill", "late-night", "commute"), (("neo-soul", 0.85),)),
    ("neo-soul", "Neo-Soul", "soul", ("rnb",), (),
     (75, 105), (1994, E), 0.45, 0.75, ("chill", "wind-down", "late-night"), (("jazz-rap", 0.6),)),
    ("gospel", "Gospel", "soul", (), (),
     (70, 130), (1930, E), 0.6, 0.9, ("uplifting",), (("gospel-house", 0.6),)),
    ("blues", "Blues", "soul", (), (),
     (60, 120), (1900, E), 0.45, 0.4, ("chill", "late-night"), (("blues-rock", 0.85),)),
    ("blues-rock", "Blues Rock", "rock", ("blues", "rock"), (),
     (90, 140), (1963, E), 0.7, 0.55, ("commute", "party"), ()),

    # ─── Jazz ──────────────────────────────────────────────────────────────
    ("jazz", "Jazz", "jazz", (), (),
     (60, 200), (1910, E), 0.5, 0.7, ("focus", "chill", "wind-down"), ()),
    ("bebop", "Bebop", "jazz", ("jazz",), (),
     (160, 300), (1940, E), 0.75, 0.65, ("focus",), (("hard-bop", 0.9),)),
    ("hard-bop", "Hard Bop", "jazz", ("bebop",), (),
     (120, 250), (1953, E), 0.7, 0.7, ("focus", "commute"), ()),
    ("cool-jazz", "Cool Jazz", "jazz", ("jazz",), (),
     (80, 140), (1949, E), 0.35, 0.75, ("chill", "wind-down", "focus"), (("modal-jazz", 0.8),)),
    ("modal-jazz", "Modal Jazz", "jazz", ("jazz",), (),
     (80, 160), (1958, E), 0.45, 0.7, ("focus", "late-night"), ()),
    ("free-jazz", "Free Jazz", "jazz", ("jazz",), (),
     (0, 0), (1959, E), 0.7, 0.4, ("focus",), (("musique-concrete", 0.4),)),
    ("jazz-fusion", "Jazz Fusion", "jazz", ("jazz", "rock"), ("fusion",),
     (100, 180), (1969, E), 0.7, 0.7, ("focus", "commute"), (("nu-jazz", 0.7),)),
    ("smooth-jazz", "Smooth Jazz", "jazz", ("jazz",), (),
     (80, 115), (1975, E), 0.3, 0.8, ("chill", "wind-down"), (("lounge", 0.7),)),
    ("swing", "Swing", "jazz", ("jazz",), ("big band",),
     (120, 200), (1930, E), 0.7, 0.85, ("party",), ()),
    ("spiritual-jazz", "Spiritual Jazz", "jazz", ("modal-jazz",), (),
     (80, 160), (1965, E), 0.5, 0.7, ("focus", "wind-down"), ()),

    # ─── Classical ─────────────────────────────────────────────────────────
    ("classical", "Classical", "classical", (), (),
     (0, 0), (1600, E), 0.4, 0.7, ("focus", "wind-down"), ()),
    ("baroque", "Baroque", "classical", ("classical",), (),
     (0, 0), (1600, 1750), 0.5, 0.75, ("focus",), ()),
    ("romantic", "Romantic", "classical", ("classical",), (),
     (0, 0), (1800, 1910), 0.55, 0.65, ("focus", "wind-down"), ()),
    ("opera", "Opera", "classical", ("classical",), (),
     (0, 0), (1600, E), 0.6, 0.6, (), ()),
    ("modern-classical", "Modern Classical", "classical", ("classical",), ("contemporary classical",),
     (0, 0), (1900, E), 0.4, 0.5, ("focus",), (("minimalism", 0.85),)),
    ("minimalism", "Minimalism", "classical", ("modern-classical",), ("minimal classical",),
     (0, 0), (1960, E), 0.3, 0.6, ("focus", "wind-down", "sleep"), (("ambient", 0.7),)),
    ("neoclassical", "Neoclassical", "classical", ("modern-classical",), ("neo-classical",),
     (0, 0), (1990, E), 0.3, 0.6, ("focus", "wind-down", "sleep"), (("ambient", 0.7), ("post-rock", 0.5))),
    ("film-score", "Film Score", "classical", ("classical",), ("soundtrack", "ost"),
     (0, 0), (1930, E), 0.5, 0.6, ("focus",), (("neoclassical", 0.7),)),

    # ─── Folk & country ────────────────────────────────────────────────────
    ("folk", "Folk", "folk", (), (),
     (80, 130), (1900, E), 0.4, 0.65, ("chill", "wind-down", "commute"), ()),
    ("singer-songwriter", "Singer-Songwriter", "folk", ("folk",), (),
     (70, 120), (1960, E), 0.35, 0.6, ("chill", "wind-down"), ()),
    ("indie-folk", "Indie Folk", "folk", ("folk", "indie-rock"), (),
     (80, 130), (1990, E), 0.4, 0.65, ("chill", "wind-down", "commute"), ()),
    ("country", "Country", "folk", (), (),
     (90, 140), (1920, E), 0.55, 0.7, ("commute", "party"), (("americana", 0.85),)),
    ("americana", "Americana", "folk", ("country", "folk"), (),
     (85, 130), (1990, E), 0.45, 0.65, ("commute", "chill"), ()),
    ("bluegrass", "Bluegrass", "folk", ("country",), (),
     (120, 180), (1940, E), 0.7, 0.8, ("commute", "party"), ()),
    ("celtic", "Celtic", "folk", ("folk",), ("celtic folk",),
     (90, 160), (1900, E), 0.55, 0.7, ("commute",), ()),

    # ─── Latin ─────────────────────────────────────────────────────────────
    ("latin", "Latin", "latin", (), (),
     (90, 130), (1900, E), 0.7, 0.8, ("party", "commute"), ()),
    ("salsa", "Salsa", "latin", ("latin",), (),
     (150, 250), (1960, E), 0.8, 0.9, ("party",), (("son-cubano", 0.85),)),
    ("son-cubano", "Son Cubano", "latin", ("latin",), (),
     (120, 180), (1900, E), 0.6, 0.85, ("chill", "party"), ()),
    ("bossa-nova", "Bossa Nova", "latin", ("latin", "jazz"), (),
     (120, 150), (1958, E), 0.3, 0.8, ("chill", "wind-down", "focus"), (("lounge", 0.6),)),
    ("samba", "Samba", "latin", ("latin",), (),
     (95, 110), (1910, E), 0.8, 0.9, ("party",), ()),
    ("reggaeton", "Reggaetón", "latin", ("latin", "dancehall"), (),
     (88, 98), (1990, E), 0.75, 0.75, ("party", "workout"), (("dembow", 0.85),)),
    ("dembow", "Dembow", "latin", ("reggaeton",), (),
     (100, 120), (1990, E), 0.85, 0.7, ("party",), ()),
    ("cumbia", "Cumbia", "latin", ("latin",), (),
     (85, 110), (1940, E), 0.6, 0.8, ("party", "commute"), ()),
    ("latin-electronic", "Latin Electronic", "latin", ("latin", "electronic"), (),
     (95, 128), (2005, E), 0.7, 0.75, ("party",), (("cumbia", 0.6), ("baile-funk", 0.6))),
    ("tango", "Tango", "latin", ("latin",), (),
     (100, 140), (1880, E), 0.55, 0.5, ("late-night",), ()),
    ("flamenco", "Flamenco", "latin", (), (),
     (90, 160), (1750, E), 0.65, 0.6, ("focus",), ()),

    # ─── Global / regional ─────────────────────────────────────────────────
    ("global", "Global", "global", (), ("world music", "world"),
     (60, 160), (1900, E), 0.55, 0.7, ("commute", "chill"), ()),
    ("reggae", "Reggae", "global", ("global",), (),
     (60, 90), (1968, E), 0.5, 0.8, ("chill", "commute"), (("dub", 0.85), ("dancehall", 0.8))),
    ("dancehall", "Dancehall", "global", ("reggae",), (),
     (90, 110), (1979, E), 0.75, 0.8, ("party",), ()),
    ("afrobeat", "Afrobeat", "global", ("global", "funk"), (),
     (100, 130), (1968, E), 0.65, 0.8, ("party", "commute"), (("afrobeats", 0.6),)),
    ("highlife", "Highlife", "global", ("global",), (),
     (100, 130), (1920, E), 0.6, 0.85, ("commute", "chill"), ()),
    ("bollywood", "Bollywood", "global", ("global",), ("filmi",),
     (90, 140), (1930, E), 0.7, 0.85, ("party",), ()),
    ("k-indie", "K-Indie", "global", ("indie-pop",), (),
     (90, 130), (2005, E), 0.45, 0.7, ("chill", "commute"), ()),
    ("fado", "Fado", "global", ("global",), (),
     (60, 100), (1820, E), 0.35, 0.3, ("late-night", "wind-down"), ()),
    ("klezmer", "Klezmer", "global", ("global",), (),
     (100, 180), (1800, E), 0.7, 0.75, ("party",), ()),
    ("qawwali", "Qawwali", "global", ("global",), (),
     (80, 140), (1300, E), 0.6, 0.8, ("focus",), (("spiritual-jazz", 0.4),)),
    ("throat-singing", "Throat Singing", "global", ("global",), (),
     (0, 0), (1000, E), 0.4, 0.5, ("focus",), (("drone", 0.6),)),
]

# ─── Moods ─────────────────────────────────────────────────────────────────
# (id, label, bpm, energy_window, ((genre_id, weight), ...))
#
# Weights are "how central is this genre to this mood", and the feed builder
# samples from the top of the list outward as the adventure knob rises. Every
# mood names at least four genres so a single unreachable one can't empty it.

MOODS = [
    ("focus", "Focus", (60, 130), (0.15, 0.6),
     (("ambient", 1.0), ("minimalism", 0.9), ("lofi-hiphop", 0.9), ("dub-techno", 0.85),
      ("minimal-techno", 0.8), ("ambient-techno", 0.8), ("neoclassical", 0.8),
      ("atmospheric-dnb", 0.7), ("drone", 0.6), ("post-rock", 0.6))),

    ("late-night", "Late night", (70, 140), (0.2, 0.7),
     (("dub-techno", 1.0), ("deep-house", 0.9), ("trip-hop", 0.85), ("future-garage", 0.85),
      ("neo-soul", 0.8), ("dark-ambient", 0.7), ("halftime-dnb", 0.7), ("three-step", 0.7),
      ("cloud-rap", 0.6), ("synthwave", 0.6))),

    ("workout", "Workout", (130, 200), (0.75, 1.0),
     (("drum-and-bass", 1.0), ("hard-techno", 0.95), ("hardstyle", 0.9), ("brostep", 0.9),
      ("neurofunk", 0.85), ("drift-phonk", 0.85), ("trap", 0.8), ("peak-time-techno", 0.8),
      ("metalcore", 0.7), ("gabber", 0.6))),

    ("party", "Party", (110, 150), (0.65, 1.0),
     (("house", 1.0), ("tech-house", 0.9), ("disco", 0.85), ("baile-funk", 0.8),
      ("uk-garage", 0.8), ("amapiano", 0.8), ("jersey-club", 0.75), ("big-room", 0.7),
      ("dancehall", 0.7), ("reggaeton", 0.7))),

    ("chill", "Chill", (60, 120), (0.2, 0.55),
     (("downtempo", 1.0), ("lounge", 0.9), ("lofi-hiphop", 0.85), ("bossa-nova", 0.8),
      ("neo-soul", 0.8), ("dream-pop", 0.75), ("organic-house", 0.7), ("smooth-jazz", 0.7),
      ("indie-folk", 0.65), ("chillwave", 0.65))),

    ("commute", "Commute", (95, 145), (0.5, 0.85),
     (("liquid-dnb", 0.9), ("synthwave", 0.85), ("boom-bap", 0.85), ("indie-rock", 0.8),
      ("melodic-house-techno", 0.8), ("nu-disco", 0.75), ("afrobeats", 0.75),
      ("city-pop", 0.7), ("progressive-house", 0.7), ("britpop", 0.6))),

    ("wind-down", "Wind down", (50, 100), (0.1, 0.45),
     (("ambient", 1.0), ("neoclassical", 0.9), ("new-age", 0.8), ("lofi-hiphop", 0.8),
      ("cool-jazz", 0.75), ("shoegaze", 0.7), ("psydub", 0.7), ("ambient-dub", 0.7),
      ("bedroom-pop", 0.65), ("singer-songwriter", 0.6))),

    ("uplifting", "Uplifting", (110, 180), (0.7, 1.0),
     (("uplifting-trance", 1.0), ("euphoric-hardstyle", 0.85), ("happy-hardcore", 0.85),
      ("gospel", 0.8), ("dance-pop", 0.8), ("motown", 0.75), ("power-metal", 0.7),
      ("future-bass", 0.7), ("vocal-trance", 0.7), ("gospel-house", 0.65))),

    ("sleep", "Sleep", (40, 80), (0.0, 0.25),
     (("ambient", 1.0), ("drone", 0.85), ("new-age", 0.85), ("minimalism", 0.8),
      ("field-recording", 0.75), ("neoclassical", 0.7), ("lowercase", 0.7),
      ("mallsoft", 0.6), ("lofi-hiphop", 0.55))),
]
