#!/usr/bin/env python3
"""
Writes app/src/main/res/values*/strings.xml from the translation table in
strings.tsv beside this script: one row per key, one column per language.

The table is the source; the XML is generated. Edit the table and rerun:

    python3 app/l10n/generate_strings.py

Every key must have every language filled in — the script refuses to write a
file with a hole in it, because Android quietly falls back to English for a
missing string and nobody notices until a user in that language does.

Rows whose key ends in `#one`, `#other` (and so on) are plural quantities;
they are grouped into one <plurals> per key.
"""
import csv, os, sys, re
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, '..', 'src', 'main', 'res')
LANGS = {  # column -> values folder
    'en': 'values', 'zh': 'values-zh-rCN', 'ja': 'values-ja', 'fr': 'values-fr',
    'es': 'values-es', 'tr': 'values-tr', 'de': 'values-de',
}
# Plural categories each language actually distinguishes (CLDR). A <plurals>
# must give exactly these: an English-style one/other pair in Japanese is
# harmless but a missing "many" in French or Spanish is a wrong number.
PLURAL_FORMS = {
    'en': ['one', 'other'], 'zh': ['other'], 'ja': ['other'], 'tr': ['one', 'other'],
    'fr': ['one', 'many', 'other'], 'es': ['one', 'many', 'other'], 'de': ['one', 'other'],
}
NON_TRANSLATABLE = {'app_name'}

def french_spacing(s):
    """French puts a space before : ; ? ! and it has to be non-breaking, or a
    narrow screen wraps the mark onto a line of its own. Written as a plain
    space in the table, it becomes U+00A0 here, so nobody has to type it."""
    return re.sub(r' ([:;?!])', '\u00a0\\1', s)

def android_escape(s):
    s = escape(s)  # & < >
    s = s.replace('\\', '\\\\').replace("'", "\\'").replace('"', '\\"')
    if s.startswith('@') or s.startswith('?'):
        s = '\\' + s
    s = s.replace('\n', '\\n')
    # aapt trims leading and trailing whitespace unless the string is quoted.
    if s != s.strip():
        s = '"' + s + '"'
    return s

def main():
    rows = list(csv.DictReader(open(os.path.join(HERE, 'strings.tsv'), encoding='utf-8'), delimiter='\t'))
    errors = []
    plurals = {}
    for r in rows:
        key = r['key']
        if '#' in key:
            base, q = key.split('#')
            plurals.setdefault(base, {})[q] = r
        for lang in LANGS:
            if '#' in key or (key in NON_TRANSLATABLE and lang != 'en'):
                continue  # plurals are checked per form below
            if not (r.get(lang) or '').strip():
                errors.append(f'{key}: no {lang}')
            if lang != 'en':
                # Every placeholder the English uses must survive translation.
                want = sorted(re.findall(r'%\d+\$[sdf]', r['en']))
                got = sorted(re.findall(r'%\d+\$[sdf]', r.get(lang) or ''))
                if want != got:
                    errors.append(f'{key}: {lang} placeholders {got} != en {want}')
    for base, forms in plurals.items():
        want = sorted(re.findall(r'%\d+\$[sdf]', forms['other']['en']))
        for lang, needed in PLURAL_FORMS.items():
            for q in needed:
                if q not in forms or not (forms[q].get(lang) or '').strip():
                    errors.append(f'{base}: {lang} plural "{q}" missing')
                    continue
                got = sorted(re.findall(r'%\d+\$[sdf]', forms[q][lang]))
                # "one" may leave the number out ("Afficher le titre"); no
                # form may invent a placeholder or drop one in "other".
                ok = set(got) <= set(want) if q == 'one' else got == want
                if not ok:
                    errors.append(f'{base}: {lang} plural "{q}" placeholders {got} != {want}')
    if errors:
        print('\n'.join(errors), file=sys.stderr)
        sys.exit(1)

    for lang, folder in LANGS.items():
        out = ['<?xml version="1.0" encoding="utf-8"?>',
               '<!-- Generated by app/l10n/generate_strings.py from app/l10n/strings.tsv. Do not edit. -->',
               '<resources>']
        seen = set()
        for r in rows:
            key = r['key']
            if '#' in key:
                base = key.split('#')[0]
                if base in seen:
                    continue
                seen.add(base)
                out.append(f'    <plurals name="{base}">')
                for q in PLURAL_FORMS[lang]:
                    text = plurals[base][q][lang]
                    if lang == 'fr':
                        text = french_spacing(text)
                    out.append(f'        <item quantity="{q}">{android_escape(text)}</item>')
                out.append('    </plurals>')
                continue
            if key in NON_TRANSLATABLE:
                if lang == 'en':
                    out.append(f'    <string name="{key}" translatable="false">{android_escape(r["en"])}</string>')
                continue
            text = french_spacing(r[lang]) if lang == 'fr' else r[lang]
            fmt = ' formatted="false"' if '%' in text and not re.search(r'%\d+\$', text) else ''
            out.append(f'    <string name="{key}"{fmt}>{android_escape(text)}</string>')
        out.append('</resources>')
        os.makedirs(os.path.join(RES, folder), exist_ok=True)
        with open(os.path.join(RES, folder, 'strings.xml'), 'w', encoding='utf-8') as f:
            f.write('\n'.join(out) + '\n')
    print(f'wrote {len(rows)} rows into {len(LANGS)} languages')

main()
